# Generated by Django 3.2.6 on 2021-08-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colonia',
            name='d_CP',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
